### ISSUE TITLE
Methane

### ISSUE THREAD

**Issue by kane1973** [VertexFloat/additionalUnits#11]
issue with Methane when i use Additional Units.
I tested it in a new savegame with no other mods installed.
I get the following error in log:
![addunit](https://github.com/4c65736975/additionalUnits/assets/97903523/24a6186e-7ec3-4f8e-9bef-c30ec781ac7f)

**Comment by 4c65736975** [comment]
Fixed

**Comment by kane1973** [comment]
fixed? still version 1.0 ?

**Comment by 4c65736975** [comment]
> fixed? still version 1.0 ?

It is already fixed, but the update has not been released yet, you would have to download the version from the dev branch not main

**Comment by kane1973** [comment]
OK thank you. so i have to wait to the update i guess?

**Comment by 4c65736975** [comment]
> is it this zip? additionalUnits-5-conflict-with-info-display-extension-mod.zip

That's right, you can put this file in mods and it should work or unpack and use modInstaller which is inside and clean mod will be installed
