### ISSUE TITLE
Water bar added

### ISSUE THREAD

**Issue by Vounar** [VertexFloat/additionalUnits#15]
### Version

1.0.0.0

### Game Version

Farming Simulator 22 (1.13.1.1)

### 👣 Steps to reproduce

water bar is added to the animal pens even when the animal doesn't need water.
Example: when playing on the Alma Missouri map animals like cows and horses have a water fill bar in the menu even though the actual structure does not have the icon and the tip area for water.
![Posnetek zaslona (317)](https://github.com/4c65736975/additionalUnits/assets/159930496/d3107b8c-ca55-4b89-a28c-34ff392a68b0)

### ⭐️ Expected Behavior

I would think that sort of thing wouldn't happen with this sort of mod

**Comment by 4c65736975** [comment]
I already know the problem, and the update has been prepared for some time, it should be ready this month ;)

**Comment by 4c65736975** [comment]
Fixed
