### ISSUE TITLE
Is it possible to be compatible with ProductionInspector?

### ISSUE THREAD

**Issue by vitalii2011** [VertexFloat/additionalUnits#35]
### Description of the new feature / enhancement

Now:
![fsScreen_2024_04_13_12_37_20](https://github.com/VertexFloat/additionalUnits/assets/41552153/8ef2c1c1-b9fd-4433-8db4-70636f350c30)

### Scenario when this would be used?

https://github.com/jtsage/FS22_ProductionInspector

**Comment by vitalii2011** [comment]
…and with “Contracts”/BetterContracts https://github.com/Mmtrx/FS22_BetterContracts
![fsScreen_2024_04_13_13_24_26](https://github.com/VertexFloat/additionalUnits/assets/41552153/acd84a99-b7e1-4b42-a1ed-0d284e85499e)

**Comment by 4c65736975** [comment]
At the moment, I do not plan to add further compatibility by myself. Please open an issue with each author asking them to add compatibility with AdditionalUnits
