### ISSUE TITLE
Precision decimal

### ISSUE THREAD

**Issue by Incompertus** [VertexFloat/additionalUnits#38]
### Version

1.0.0.1

### Game Version

Farming Simulator 22 (1.13.1.1)

### 👣 Steps to reproduce

changing precision decimal dont do anything

**Comment by 4c65736975** [comment]
I am aware of this, in the previous version this option changed precision everywhere. However, there are some places in the game where this precision is set permanently (e.g. Fill Level Display), so I decided that in this version, the precision option will change this precision only where it is not hardcoded.

For now, I don't plan any changes in this direction or any other, only fixing possible mistakes (I don't take this into account). At this point the modification is complete for me.
