### ISSUE TITLE
Conflict with Info Display Extension mod

### ISSUE THREAD

**Issue by vitalii2011** [VertexFloat/additionalUnits#5]
- https://www.farming-simulator.com/mod.php?lang=en&country=ru&mod_id=239604&title=fs2022 
![fsScreen_2023_04_29_09_50_42](https://user-images.githubusercontent.com/41552153/235292306-a92f77d6-b16e-4a76-86fd-e8544c5038a7.png) 
- The name "Liters" cannot be edited (in game)?
![fsScreen_2023_04_29_11_08_21](https://user-images.githubusercontent.com/41552153/235292764-a427cf02-d46b-43f0-8f61-7425d9a6589c.png) 
![fsScreen_2023_04_29_10_38_10](https://user-images.githubusercontent.com/41552153/235292875-8947db20-dbc1-4c1f-b9bd-966ed2c506ff.png)
- Is it possible to add space for 2 characters in the 'Short name' field?
![fsScreen_2023_04_29_11_09_08](https://user-images.githubusercontent.com/41552153/235292836-665cd926-1b17-4e9b-b5e2-224d5b131be9.png)

**Comment by KingArthurLV** [comment]
I can canfirm, that I have same issue. Information about capacity also disapeared in production, animal pens and storage menus.

**Comment by 4c65736975** [comment]
1. I'll check it out, I think some of the overrides conflict with the overrides of this extension or I just need to override the Info 
Display extension's functions.
2. Yes, it's not possible because it's the default unit of the game and I've disabled the option to edit it.
3. Yes, it's possible I just didn't thought that short name could be so long :D

**Comment by vitalii2011** [comment]
:) That's right. There is no abbreviation for "pound" in Russian.

**Comment by vitalii2011** [comment]
- Maybe it would be correct to add a "default" space before all "shortName"? 
![fsScreen_2023_04_30_15_21_29](https://user-images.githubusercontent.com/41552153/235356627-bb7b5fe6-9c26-495b-8870-08b3f0638a31.png)
- Units of measure are not "picked up" in the Target Fill Level mod https://www.farming-simulator.com/mod.php?mod_id=231717 .
- 
![fsScreen_2023_04_30_16_40_26](https://user-images.githubusercontent.com/41552153/235357639-9353db84-3365-45fd-ae91-cf80839c44fe.png)

**Comment by 4c65736975** [comment]
1. It has default spacing.
2. I will add compatibility with this in upcoming update.

**Comment by 4c65736975** [comment]
Due to the need to change the core InfoDisplayExtension elements for support, no support has been added for this modification.

Support added for TargetFillLevel and StrawHarvestPack

**Comment by 4c65736975** [comment]
Beta version of [InfoDisplayExtension](https://github.com/Achimobil/FS22_InfoDisplayExtension) is released, support for AdditionalUnits is added, please download this version to test it with.

**Comment by vitalii2011** [comment]
InfoDisplayExtension 1.7.1.1 without Additional Units 1.0.0.1: 
![fsScreen_2024_04_07_08_57_10](https://github.com/VertexFloat/additionalUnits/assets/41552153/e18567f2-e7d4-49a6-8588-e0f0491fca05)
With: 
![fsScreen_2024_04_07_08_52_41](https://github.com/VertexFloat/additionalUnits/assets/41552153/fb139021-3b07-46e1-9b5e-acfa92f8907a)
[log.txt](https://github.com/VertexFloat/additionalUnits/files/14896010/log.txt)

**Comment by 4c65736975** [comment]
> InfoDisplayExtension 1.7.1.1 without Additional Units 1.0.0.1: ![fsScreen_2024_04_07_08_57_10](https://private-user-images.githubusercontent.com/41552153/320257524-e18567f2-e7d4-49a6-8588-e0f0491fca05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0Nzc5ODgsIm5iZiI6MTcxMjQ3NzY4OCwicGF0aCI6Ii80MTU1MjE1My8zMjAyNTc1MjQtZTE4NTY3ZjItZTdkNC00OWE2LTg1ODgtZTBmMDQ5MWZjYTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDA4MTQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjYjQ3YWRmNGE2MDQ5NzViODBmZjY4NGJjOWQwODRhMjVjZTNiYjczZmZmZmFkYjcwOWVhZGZmMjllMjk4NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J6wn39kq5o40Vf912RrCy460cdCTgeXvQfaQpag5NwI) With: ![fsScreen_2024_04_07_08_52_41](https://private-user-images.githubusercontent.com/41552153/320257597-fb139021-3b07-46e1-9b5e-acfa92f8907a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0Nzc5ODgsIm5iZiI6MTcxMjQ3NzY4OCwicGF0aCI6Ii80MTU1MjE1My8zMjAyNTc1OTctZmIxMzkwMjEtM2IwNy00NmUxLTliNWUtYWNmYTkyZjg5MDdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDA4MTQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjOWVhMGZiYWVmMTczMjdmZjJiNTQ4MTcxMTA0YzBhMzhjNDcwZGMyNmEyODgxMjVkODY1ZjAwNzk1ZjFkYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gJRY_iIjWWqtjLEsfrg9AYAPL0LXgiZ-RLibPtqXb2E) [log.txt](https://github.com/VertexFloat/additionalUnits/files/14896010/log.txt)

Do you have any other modifications related to ProductionPoints enabled? Because it looks like a conflict with one

**Comment by vitalii2011** [comment]
Only InfoDisplayExtension 1.7.1.1 and Additional Units 1.0.0.1, when turn on production, the HUD stops displaying: 

https://github.com/VertexFloat/additionalUnits/assets/41552153/d8ed52bd-c602-4bf4-9a45-6e602fa886fb

[log.txt](https://github.com/VertexFloat/additionalUnits/files/14896507/log.txt)

**Comment by 4c65736975** [comment]
> Only InfoDisplayExtension 1.7.1.1 and Additional Units 1.0.0.1, when turn on production, the HUD stops displaying:
> 
>  FarmingSimulator2022Game.2024-04-07.11-50-20.mp4 
> [log.txt](https://github.com/VertexFloat/additionalUnits/files/14896507/log.txt)

It looks like something is wrong on your end, because everything works fine for me. Please check it on a clean savegame with only these two modifications

**Comment by vitalii2011** [comment]
Unfortunately, even this: 
[mods.zip](https://github.com/VertexFloat/additionalUnits/files/14896717/mods.zip)
![fsScreen_2024_04_07_12_49_25](https://github.com/VertexFloat/additionalUnits/assets/41552153/b4f12a4a-42f1-46bd-91fe-c5c44ec2978f)
same problem: 
[modSettings.zip](https://github.com/VertexFloat/additionalUnits/files/14896726/modSettings.zip)
[log.txt](https://github.com/VertexFloat/additionalUnits/files/14896728/log.txt)

**Comment by 4c65736975** [comment]
> Unfortunately, even this: [mods.zip](https://github.com/VertexFloat/additionalUnits/files/14896717/mods.zip) ![fsScreen_2024_04_07_12_49_25](https://private-user-images.githubusercontent.com/41552153/320272663-b4f12a4a-42f1-46bd-91fe-c5c44ec2978f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0ODY4MTQsIm5iZiI6MTcxMjQ4NjUxNCwicGF0aCI6Ii80MTU1MjE1My8zMjAyNzI2NjMtYjRmMTJhNGEtNDJmMS00NmJkLTkxZmUtYzVjNDRlYzI5NzhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDEwNDE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3ZGU3MjgzZGI2OWMzNjUxOTc1NTVjYmFmYmYwYjg0NGI4NTdhYzExZDJlMWQyYTk5NDc1Y2U3YjA3ZDY2ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1Oh7Hxi67HRhFs9u8VgyzphVzqZ5JkI5Xb0T_ymcCoY) same problem: [modSettings.zip](https://github.com/VertexFloat/additionalUnits/files/14896726/modSettings.zip) [log.txt](https://github.com/VertexFloat/additionalUnits/files/14896728/log.txt)

Fixed, let me know if now everything works fine ;) [v1.0.0.1](https://github.com/VertexFloat/additionalUnits/releases/tag/v1.0.0.1)

**Comment by vitalii2011** [comment]
Everything seems to be fine. Thanks!

**Comment by vitalii2011** [comment]
But now the abbreviated names of units of measurement are not displayed.

**Comment by 4c65736975** [comment]
> But now the abbreviated names of units of measurement are not displayed.

Yeah I know, the problem was with my implementation of support in InputDisplayExtension, download [this](https://github.com/VertexFloat/FS22_InfoDisplayExtension/tree/additionalUnits-fix-unit) version and it should works.

**Comment by vitalii2011** [comment]
I haven’t seen any problems with Info Display Extension 1.7.1.2 (yet ;) ). Thanks.
