### ISSUE TITLE
DEF/Adblue not recognized. 

### ISSUE THREAD

**Issue by talianagisan** [VertexFloat/additionalUnits#8]
Greetings. The DEF fill type is not recognized. 

Normally this is an invisible unit ingame similar to air but mods such as https://www.farming-simulator.com/mod.php?lang=fr&country=be&mod_id=129833 enable it to be consume and refilled in tractors. 

Could this be corrected? All other features work great.

**Comment by 4c65736975** [comment]
It’s not showing cause this fillType is originally hidden. I will add unit support for it to be visible when you have this mod enabled in the upcoming update 👊

**Comment by talianagisan** [comment]
> It’s not showing cause this fillType is originally hidden. I will add unit support for it to be visible when you have this mod enabled in the upcoming update 👊

Thank you very much. This will be a big help.

**Comment by 4c65736975** [comment]
Added
